### ISSUE TITLE
UML Diagram

### ISSUE THREAD

**Issue by DimaPindrik** [DimaPindrik/Team.F#12]
Build a UML diagram for our mvc PHP server

**Comment by TimurMisharin** [comment]
Which kind of diagram you need? Use case or Class diagram???

**Comment by DimaPindrik** [comment]
Just a standart Class diagram, If you wish make a Use case ad well

**Comment by TimurMisharin** [comment]
I think at this stage we can't build a Class diagram, because we don't planing the logic of the project.

**Comment by DimaPindrik** [comment]
So this task can wait.
